site_name: Brett Magill
site_description: Personal site & notes
site_url: https://thatbrettmagill.github.io

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
  features:
    - navigation.top        # header nav instead of left sidebar
    - navigation.instant    # snappier page loads
    - content.code.copy     # copy button on code blocks

nav:
  - Home: index.md
  - Projects: projects.md
  - Writing: writing.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/hyacsho
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/dreadlymaw
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/brettmagill

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.wikilinks:
      base_url: ""
      end_url: ".html"
      html_class: wikilink"
