site_name: Brett Magill
site_description: Personal site & notes
site_url: https://thatbrettmagill.github.io

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Light mode
  features:
    - navigation.top
    - navigation.instant
    - content.code.copy

nav:
  - Home: index.md
  - Projects: projects.md
  - Writing: writing.md
  - About: about.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/hyacsho
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/dreadlymaw
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/brettmagill
  copyright: "© 2025 Brett Magill"

markdown_extensions:
  - footnotes
  - admonition
