site_name: Brett Magill
site_description: Personal site & notes
site_url: https://thatbrettmagill.github.io

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
nav:
  - Home: index.md
  - Projects: projects.md
  - Writing: writing.md
  - About: about.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/hyacsho
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/dreadlymaw
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/brettmagill
  font:
      text: Inter
      code: JetBrains Mono
  copyright: "© 2025 Brett Magill"

markdown_extensions:
  - footnotes
  - admonition

extra_css:
  - assets/overrides.css

extra_javascript:
  - assets/search-button.js
